<?xml version="1.0" encoding="utf-8"?><Database Name="u0992410_EMM_1.0" Class="RateDataContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=31.31.196.89;Initial Catalog=u0992410_EMM_1.0;Persist Security Info=True;User ID=u0992410_emm_app" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="u0992410_vitek4051.Positions_TS" Member="Positions_TS">
    <Type Name="Positions_TS">
      <Column Name="position" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="rate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>