// <auto-generated />
namespace EMM_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewIdentityFiels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewIdentityFiels));
        
        string IMigrationMetadata.Id
        {
            get { return "202006231319324_NewIdentityFiels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
